#!/bin/bash -l

FITS_BASE_FOLDER="./fits-lightq"

MODELNAME=$1
EPS=$2
MEVAL=$3
MINUITPREC=$4
FITPAR=$5
NUMPAR_STRING="-cueps-$EPS-cumeval-$MEVAL-minuprec-$MINUITPREC-fitpar-$FITPAR"
RUN_STRING="$MODELNAME$NUMPAR_STRING"
#echo $RUN_STRING
#exit 1

SBATCH_FILE="$FITS_BASE_FOLDER/echo_sbatch_scripts/$RUN_STRING.sh"
echo $SBATCH_FILE

INPUT_FILE="$FITS_BASE_FOLDER/echo_inputs/$MODELNAME-fit.sh"

echo "#!/bin/bash -l" > $SBATCH_FILE
echo "#SBATCH -o $FITS_BASE_FOLDER/out/$MODELNAME/fit_QCGam-$NUMPAR_STRING-%j.txt" >> $SBATCH_FILE
cat $INPUT_FILE >> $SBATCH_FILE

echo "# fit NUM settings" >> $SBATCH_FILE
CUBAMTHD="suave"
echo "CUBAMTHD="'"'"$CUBAMTHD"'"' >> $SBATCH_FILE
echo "EPS=$EPS" >> $SBATCH_FILE
echo "MEVAL=$MEVAL" >> $SBATCH_FILE
echo "MINUITPREC=$MINUITPREC" >> $SBATCH_FILE
echo "FITPAR=$FITPAR" >> $SBATCH_FILE

echo 'echo FIT HERA DATA $SCHEME $BK $RC $Z2BOUND $BOUNDLOOP $QSSQR $CSQR $GAMMA $X0IF $X0BK $EC $TYPVIRTQ02 $Y0 $ETA0 $CUBAMTHD $EPS $MEVAL $MINUITPREC $FITPAR' >> $SBATCH_FILE
echo 'CUBACORES=0 ./fitex $SCHEME $BK $RC $Z2BOUND $BOUNDLOOP $QSSQR $CSQR $GAMMA $X0IF $X0BK $EC $TYPVIRTQ02 $Y0 $ETA0 $CUBAMTHD $EPS $MEVAL $MINUITPREC $FITPAR' >> $SBATCH_FILE
#echo 'seff $SLURM_JOBID' >> $SBATCH_FILE

#cat $SBATCH_FILE
#actual final command
sbatch $SBATCH_FILE


